export const projectsList = [
  {
    title: "Plain Basic T-Shirt - Number 1",
    price: 150000,
    rating: "4.6",
    sold: 234,
    variant: [
      { color: "Black", imageUrl: "/kaos.png" },
      { color: "White", imageUrl: "/kaos.png" },
      { color: "Purple", imageUrl: "/kaos.png" },
      { color: "Blue", imageUrl: "/kaos.png" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Plain Basic T-Shirt - Number 2",
    price: 200000,
    rating: "4.8",
    sold: 632,
    variant: [
      { color: "Black", imageUrl: "/kaos.png" },
      { color: "White", imageUrl: "/kaos.png" },
      { color: "Purple", imageUrl: "/kaos.png" },
      { color: "Blue", imageUrl: "/kaos.png" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Plain Basic T-Shirt - Number 3",
    price: 550000,
    rating: "4.3",
    sold: 152,
    variant: [
      { color: "Black", imageUrl: "/kaos.png" },
      { color: "White", imageUrl: "/kaos.png" },
      { color: "Purple", imageUrl: "/kaos.png" },
      { color: "Blue", imageUrl: "/kaos.png" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Plain Basic T-Shirt - Number 4",
    price: 600000,
    rating: "4.2",
    sold: 61,
    variant: [
      { color: "Black", imageUrl: "/kaos.png" },
      { color: "White", imageUrl: "/kaos.png" },
      { color: "Purple", imageUrl: "/kaos.png" },
      { color: "Blue", imageUrl: "/kaos.png" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Plain Basic T-Shirt - Number 5",
    price: 150000,
    rating: "4.9",
    sold: 1052,
    variant: [
      { color: "Black", imageUrl: "/kaos.png" },
      { color: "White", imageUrl: "/kaos.png" },
      { color: "Purple", imageUrl: "/kaos.png" },
      { color: "Blue", imageUrl: "/kaos.png" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Plain Basic T-Shirt - Number 6",
    price: 300000,
    rating: "4.7",
    sold: 128,
    variant: [
      { color: "Black", imageUrl: "/kaos.png" },
      { color: "White", imageUrl: "/kaos.png" },
      { color: "Purple", imageUrl: "/kaos.png" },
      { color: "Blue", imageUrl: "/kaos.png" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
];
